New install
BEAMRobotics/beam_install_scripts pull request #63
Opened 2022-07-25 22:16 UTC by Hateley123

finalized install scripts they work on virtual machine

2022-07-25 23:27 UTC, adthoms requested changes
@Hateley123 Looks good. I have left comments concerning: 
1) minor fixes to the installation 
2) comments to be removed before merging.

Also, as a rule of thumb, commits and branches should describe the action you are taking when updating a code base. You can use terms such as fix, update, deprecate, refactor, add, remove, etc. when writting a commit message. I did not do a good job in naming commits in this branch since I planned on squashing and merging all commits, though it is something to keep in mind.

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +  sudo apt-get install sharutils
you have these lines alread in the main install script, lines 90 and 91 should be removed OR better yet, you can remove the lines in the main install.bash as it appears these installs are only required for ig-handle

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +  echo "spinnaker installed"
Before merginging into master, these blocks of code asking if you would like to continue should be removed

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
>      # Eventually replace with better links. Currently in adthoms Dropbox
delete line

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +      # gets the file for spinnekar from the google drive folder we have
good example of over commenting. These comments should be removed before merging

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +      gdown --id 1se0fe_gu2IOxQHwVEdKLcOANbWdqoAAi
lines 189-192 are redunt and should be removed

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +      #rm -rf spinnaker-2.0.0.146-Ubuntu16.04-amd64-pkg.tar.gz?dl=0
this line should be kept. You are simply removing the .tar.gz file since it has been unpacked

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +     gdown --id 1_nT47nHHy6ugRxHH4frLV29wgCRhSRGF
remove lines 195-196

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +  echo "Installng arduino and Teensyduino"
echo "Installng arduino and Teensyduino..."

2022-07-25 23:27 UTC, adthoms commented on install_ig2.bash
> +    MT_DIR="MTIsoftware"
remove lines 105-112 as these lines are included in the `install_mti_sdk()` function

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +  if [ ! -d "$MT_DIR" ]; then
replace lines 280-282 `mkdir -p $MT_DIR`

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +  # creates a directory to store the MTI software
overcommenting. Comments should be removed before merging into master

2022-07-25 23:27 UTC, adthoms commented on install.bash
> +    install_gazebo
for now, we can remove line 125. I did this, though I plan on moving any simulation into a better maintained fork of an open source simulator

2022-07-25 23:27 UTC, adthoms commented on robot_dependencies_install.bash
> +  rm -rf MT_Software_suite_linux-x64_2021.2.tar.gz
move line 295 to after line 289 and add:

```
rm -rf mtmanager_linux-x64_2021.2.tar.gz
rm -rf magfieldmapper_linux-x64_2021.2.tar.gz
``
in its place

2022-07-26 01:24 UTC, adthoms commented
Please update the README.md to reflect additional installs for development machines and beam robots

2022-07-26 17:22 UTC, Hateley123 commented on install_ig2.bash
>      echo "INSTALL COMPLETE. YOU WILL NEED TO INSTALL THE MTI SOFTWARE AVAILABLE HERE: "
wait I thought we are not even using this file? shouldnt i just delete the entire file?

2022-07-26 18:57 UTC, adthoms commented on install_ig2.bash
>      echo "INSTALL COMPLETE. YOU WILL NEED TO INSTALL THE MTI SOFTWARE AVAILABLE HERE: "
yes delete install_ig2.bash

2022-07-26 18:57 UTC, adthoms commented on install_ig2.bash
> +    MT_DIR="MTIsoftware"
delete install_ig2.bash

2022-07-26 19:01 UTC, adthoms commented on robot_dependencies_install.bash
> +      rm -rf spinnaker-2.0.0.146-Ubuntu16.04-amd64-pkg.tar.gz?dl=0
`rm -rf spinnaker-2.0.0.146-Ubuntu16.04-amd64-pkg.tar.gz`

2022-07-26 19:02 UTC, Hateley123 commented on install_ig2.bash
> +    MT_DIR="MTIsoftware"
okay it is deleted on my end. The software is currently running so i can start testing the esnors so when its done ill push the branch up with the deleted files

2022-07-26 19:02 UTC, adthoms commented on robot_dependencies_install.bash
> +  rm -rf MT_Software_suite_linux-x64_2021.2.tar.gz
move this line before `cd MT_Software_Suite_linux-x64_2021.2`

2022-07-26 21:58 UTC, Hateley123 commented on robot_dependencies_install.bash
> +  rm -rf MT_Software_suite_linux-x64_2021.2.tar.gz
you cant. The other tar files are inside the mt software suite volde so u have to cd into them tinorder to access the other files.

2022-07-26 22:17 UTC, adthoms commented on robot_dependencies_install.bash
> +  rm -rf MT_Software_suite_linux-x64_2021.2.tar.gz
ok, so long as all `.tar.gz` get removed after they have been unpacked

2022-07-26 23:06 UTC, adthoms commented on robot_dependencies_install.bash
> +      gdown --id 1se0fe_gu2IOxQHwVEdKLcOANbWdqoAAi
I still do not understand why you are downloading the SDK twice. Lines 171-173 and lines 176-178 should be removed

2022-07-26 23:07 UTC, adthoms commented on robot_dependencies_install.bash
> +  echo "Installing arduino and Teensyduino"
`echo "Installing arduino and Teensyduino..."`

2022-07-26 23:08 UTC, adthoms commented on robot_dependencies_install.bash
> +
`echo "arduino and Teensyduino successfully installed."`

2022-07-26 23:08 UTC, adthoms commented on robot_dependencies_install.bash
> +      mv Windows_XP_32_DT100.ova Windows_XP_32_DT100.ova
remove this line

2022-07-26 23:08 UTC, adthoms commented on robot_dependencies_install.bash
> +
remove space

2022-07-26 23:08 UTC, adthoms commented on robot_dependencies_install.bash
> +  cd MT_Software_Suite_linux-x64_2021.2
add space above line 248

2022-07-26 23:09 UTC, adthoms commented on robot_dependencies_install.bash
> +  cd $MT_DIR
add space above line 244

2022-07-26 23:11 UTC, adthoms commented on robot_dependencies_install.bash
> +  # creates a directory to store the MTI software
remove this comment

2022-07-26 23:12 UTC, adthoms commented on robot_dependencies_install.bash
> +  # creates a directory to store the MTI software
echo "Installing MTI SDK..."

2022-07-26 23:12 UTC, adthoms commented on robot_dependencies_install.bash
> +
echo "MTI SDK successfully installed."

2022-07-26 23:15 UTC, adthoms commented on robot_dependencies_install.bash
>    echo "Installing rosserial..."
delete lines 188 and 191 and move lines 189 and 190 below `echo "Installing arduino and Teensyduino..."`

2022-07-26 23:15 UTC, adthoms commented on robot_dependencies_install.bash
>    echo "Installing dt100 dependencies..."
`echo "Installing dt100 driver and dependencies..."`

2022-07-26 23:15 UTC, adthoms commented on robot_dependencies_install.bash
>    echo "dt100 dependencies successfully installed."
echo "dt100 drive and dependencies successfully installed."

2022-07-26 23:28 UTC, adthoms commented on README.md
>  - Spinnaker 2.0.0.146
- [ig_handle](https://github.com/BEAMRobotics/ig_handle) driver (master branch) 
-- Spinnaker 2.0.0.146 (xenial) / Spinnaker 2.4.0.143 (bionic)
-- MTI Software Suite Linux 2021.2
-- arduino-1.8.13-linux64

- [DT 100](https://github.com/BEAMRobotics/dt100_driver) driver (master branch) 
-- Virtual Box 6.1
-- Windows_XP_32_DT100.ova (Windows XP virtual machine containing DT100_v1_05_07.exe)

2022-07-26 23:30 UTC, adthoms commented on install.bash
> +
delete this line

2022-07-26 23:30 UTC, adthoms commented on install.bash
> +
delete line 132-133

2022-07-26 23:30 UTC, adthoms commented on install.bash
> +
delete line 138

2022-07-26 23:30 UTC, adthoms commented on install.bash
> +
delete lines 141-142

2022-07-26 23:31 UTC, adthoms commented on install.bash
> +      # executes the main install scripts for the robot
delete this comment. Also line 145 does not "execute the main install scripts for the robot", it sources the robot_dependencies_install.bash script

2022-07-26 23:32 UTC, adthoms commented on install.bash
> +        # contains the drivers for the hand held lidar scanner
remove this comment

2022-07-26 23:32 UTC, adthoms commented on install.bash
> +        # same drivers are the handle bu this is for the lidar system that is not hand held. Although this code repeats it is done to seperate the systems
delete this comment

2022-07-26 23:32 UTC, adthoms commented on robot_dependencies_install.bash
> +
delete lines 12-13

2022-07-26 23:33 UTC, adthoms commented on robot_dependencies_install.bash
>  clone_ros_drivers()
you can delete this entire function

2022-07-26 23:35 UTC, adthoms commented on robot_dependencies_install.bash
> +  echo "Installing Ig Handle files"
`echo "Installing ig-handle driver and dependencies..."`

2022-07-26 23:36 UTC, adthoms commented on robot_dependencies_install.bash
> +  pip install gdown
remove lines 89-90 since gdown is installed in the main function of `install.bash`

2022-07-26 23:36 UTC, adthoms commented on robot_dependencies_install.bash
> +  # we only want these to be called if we use install_ig_handle
remove comment

2022-07-26 23:37 UTC, adthoms commented on robot_dependencies_install.bash
> +  # we only want these to be called if we use install_ig_handle
or you can write a more informative comment such as # install dependencies

2022-07-26 23:37 UTC, adthoms commented on robot_dependencies_install.bash
> +      # extracts the files we have retrieved and places them in a directory with the given file names
remove comment

2022-07-26 23:37 UTC, Hateley123 commented on robot_dependencies_install.bash
> +  cd MT_Software_Suite_linux-x64_2021.2
why do you want spaces above certain things but not between others are u trying to seperate blocks of code?

2022-07-26 23:39 UTC, adthoms commented on robot_dependencies_install.bash
>    echo "Installing dt100 dependencies..."
you still need to clone the dt100 driver as per [issue](https://github.com/BEAMRobotics/beam_install_scripts/issues/59) item 6

2022-07-26 23:41 UTC, adthoms commented on robot_dependencies_install.bash
> +      # extracts the files we have retrieved and places them in a directory with the given file names
our you can make a more descriptive comment such as # download spinnaker SDK from sri_lab/robotics/software/apis/spinnaker-2.4.0.143-Ubuntu18.04-amd64-pkg.tar.gz

2022-07-26 23:41 UTC, adthoms commented on robot_dependencies_install.bash
> +      # extracts the files we have retrieved and places them in a directory with the given file names
this can be done similiarly for other gdown commands so people in the lab know what ID corresponds to what file

2022-07-26 23:47 UTC, adthoms commented on robot_dependencies_install.bash
> +  cd MT_Software_Suite_linux-x64_2021.2
Yes, we do not have an official spacing convention enforced for `.bash` files, though blocks of code should be logically connected

2022-07-26 23:48 UTC, adthoms commented on robot_dependencies_install.bash
> +      mv Windows_XP_32_DT100.ova Windows_XP_32_DT100.ova
add comment `# download Windows XP 32 DT100 virtual machine from sri_lab/robotics/software/vms/Windows_XP_32_DT100.ova` above line 228

2022-07-27 00:10 UTC, adthoms requested changes
@Hateley123 I'm leaving this as my final review. Please address comments and ping me. Once my comments are addressed, I will test the instllation myself before merging.

2022-07-27 00:10 UTC, adthoms commented on install.bash
>        fi
should add an else condition warning the user that the specified Beam Robot does not exist and no robot drivers/dependencies were installed.

2022-07-27 00:10 UTC, adthoms commented on install.bash
> +
delete lines 180-183

2022-07-27 00:10 UTC, adthoms commented on robot_dependencies_install.bash
> +
remove line 85

2022-07-27 00:10 UTC, adthoms commented on robot_dependencies_install.bash
> +
delete this line

2022-07-27 00:10 UTC, adthoms commented on robot_dependencies_install.bash
> +
delete this line

2022-07-27 00:10 UTC, adthoms commented on robot_dependencies_install.bash
> +      # extracts the files we have retrieved and places them in a directory with the given file names
delete this comment

2022-07-27 00:10 UTC, adthoms commented on robot_dependencies_install.bash
> +      gdown --id 1_nT47nHHy6ugRxHH4frLV29wgCRhSRGF
add comment `# download Spinnaker SDK from sri_lab/robotics/software/apis/spinnaker-2.4.0.143-Ubuntu18.04-amd64-pkg.tar.gz`

2022-07-27 00:10 UTC, adthoms commented on robot_dependencies_install.bash
>        echo "Importing virtual machine..."
replace with `# download Windows XP 32 DT100 virtual machine from sri_lab/robotics/software/vms/Windows_XP_32_DT100.ova`

2022-07-27 16:15 UTC, Hateley123 commented on robot_dependencies_install.bash
> +      gdown --id 1se0fe_gu2IOxQHwVEdKLcOANbWdqoAAi
we are not downloading it twice. Its similiar to why u have install_ighandle function twice. The first instance is if you have to make a directory and then install it. The second think is if you have folder already made then it says it already exists and installs everything. I can delete it if you want but im pretty sure this is your code and knowing you i think thats why u did it twice. Its not efficient but it is descriptive. If you still want it changed let me know

2022-07-27 16:18 UTC, Hateley123 commented on robot_dependencies_install.bash
> +      mv Windows_XP_32_DT100.ova Windows_XP_32_DT100.ova
you want me to remove the gdown line? I thought u wanted me to get the file from google drive thats the issue you assigned to me.

2022-07-27 16:43 UTC, Hateley123 commented on robot_dependencies_install.bash
>  clone_ros_drivers()
are the ross drivers not needed anymore or are they suppose to be in the ighandle function. is that what u meant by depricate

2022-07-27 16:47 UTC, Hateley123 commented on install.bash
> +    sudo apt install python-pip
okay i did that but why its like one line of code.

2022-07-27 16:49 UTC, Hateley123 commented on install.bash
> +    sudo apt install python-pip
wouldnt it make more sense and be more efficient to just have one function that installs pip and gdown instead of one that installs pip and another that installs gdown

2022-07-27 17:11 UTC, Hateley123 commented
@adthoms I made most of the changes except the ones where i replied back to you i am still waiting for response. I also sent you a message on slack.

2022-07-27 23:53 UTC, adthoms commented on robot_dependencies_install.bash
> +      gdown --id 1se0fe_gu2IOxQHwVEdKLcOANbWdqoAAi
this is the original code on my branch, from which you made the `new_install` branch

```
install_spinnaker_sdk()
{
  echo "Installing spinnaker SDK..."
  LB_DIR="spinnaker"
  mkdir -p $DEPS_DIR
  cd $DEPS_DIR
  sudo apt-get install libusb-1.0-0 libgtkmm-2.4-dev
  sudo apt-get install ros-$ROS_DISTRO-image-common
  sudo apt-get install ros-$ROS_DISTRO-image-exposure-msgs
  sudo apt-get install ros-$ROS_DISTRO-wfov-camera-msgs
  sudo apt-get install ros-$ROS_DISTRO-image-proc
  # sudo apt-get install libavcodec57 libavformat57 libswscale4 libswresample2 libavutil55 

  if [ ! -d "$LB_DIR" ]; then
    echo "Don't have Spinnaker SDK Directory, creating & downloading SDK..."
    mkdir -p $LB_DIR
    cd $LB_DIR
    # Eventually replace with better links. Currently in adthoms Dropbox
    if [ "$ROS_DISTRO" = "kinetic" ]; then
      wget https://drive.google.com/file/d/1se0fe_gu2IOxQHwVEdKLcOANbWdqoAAi/view?usp=sharing.gz?dl=0        
      tar -xvf spinnaker-2.0.0.146-Ubuntu16.04-amd64-pkg.tar.gz?dl=0
      rm -rf spinnaker-2.0.0.146-Ubuntu16.04-amd64-pkg.tar.gz?dl=0      
      cd spinnaker-2.0.0.146-amd64/
    elif [ "$ROS_DISTRO" = "melodic" ]; then
      wget https://drive.google.com/file/d/1_nT47nHHy6ugRxHH4frLV29wgCRhSRGF/view?usp=sharing.gz?dl=0        
      tar -xvf spinnaker-2.4.0.143-Ubuntu18.04-amd64-pkg.tar.gz?dl=0
      rm -rf spinnaker-2.4.0.143-Ubuntu18.04-amd64-pkg.tar.gz?dl=0      
      cd spinnaker-2.4.0.143-amd64/
    fi
    sudo sh install_spinnaker.sh
    echo "Spinnaker SDK successfully installed."
  else
    echo "Already have spinnaker folder..."
    cd $LB_DIR
    if [ "$ROS_DISTRO" = "kinetic" ]; then
      cd spinnaker-2.0.0.146-amd64/
    elif [ "$ROS_DISTRO" = "melodic" ]; then
      cd spinnaker-2.4.0.143-amd64/
    fi
    sudo sh install_spinnaker.sh
    echo "Spinnaker SDK successfully installed."
  fi
}
```
you can see that the main if statement first checks if the `LB_DIR` exists. If it does not exist, then the directory is created and the appropriate SDK (according to the version of ubuntu on the machine) is downloaded and installed. If the directory does exist, this means that the SDKs have already been downloaded, so there is no need to redownload.

2022-07-27 23:54 UTC, adthoms commented on robot_dependencies_install.bash
> +      mv Windows_XP_32_DT100.ova Windows_XP_32_DT100.ova
no, this comment directly refers to line 229. The line `mv Windows_XP_32_DT100.ova Windows_XP_32_DT100.ova` does nothing

2022-07-27 23:57 UTC, adthoms commented on robot_dependencies_install.bash
>  clone_ros_drivers()
clone_ros_drivers() is deprecated and thus no longer serves a function in the installation process.

2022-07-28 00:00 UTC, adthoms commented on install.bash
> +    sudo apt install python-pip
In terms of efficiency, there are practically zero time savings when having everything in one function. We prefer to keep things modular and have install functions do a particular task. This helps with readability and maintainability.

2022-07-28 06:00 UTC, merged